name: codingame
version: 0.0.1
description: A sample command-line application.
#author: Brian Grey <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.15.3
